spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/blogus
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: mail-user
    password: mail-password
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
token:
  secret: ykIQjX6bZSHO0mkjkNL8U3Ht9NtzjtIZ
