spring:
  profiles:
    active: dev
    include: secret
  data:
    web:
      pageable:
        default-page-size: 4
        one-indexed-parameters: true
blogus:
  host: http://localhost:8080
  client: http://localhost:3000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/blogus
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
token:
  secret: ykIQjX6bZSHO0mkjkNL8U3Ht9NtzjtIZ
