name: Deploy Blogus
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      backend-directory: ./blogus-backend
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Grant execute permisson for mvnw
        run: chmod +x mvnw
        working-directory: ${{ env.backend-directory }}
      - name: Make jars of the Blogus api-server with Maven
        run: mvnw -q clean package -DskipTests
        working-directory: ${{ env.backend-directory }}
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ela87/blogus-client ./client
      - run: docker build -t ela87/blogus-nginx ./nginx
      - run: docker build -t ela87/blogus-api ./blogus-backend
      - run: docker push ela87/blogus-client
      - run: docker push ela87/blogus-nginx
      - run: docker push ela87/blogus-api
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: blogus
          environment_name: Blogus-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-471295099456
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
